name: Translate Vietnamese to English
permissions:
  contents: write

on:
  pull_request:
    paths:
      - "Currency-Converter/vi.lproj/Localizable.strings" # Trigger khi Localizable.strings thay đổi trong vi.lproj
  workflow_dispatch: # Cho phép kích hoạt thủ công

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install deep_translator

      - name: Run translation script
        run: |
          python Currency-Converter/translate.py

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update English translations" || echo "No changes to commit"
          git push https://github-actions[bot]:${{ secrets.ENV_GITHUB_TOKEN }}@github.com/nguyenvuong1309/Currency-Converter.git
        env:
          # Sử dụng GITHUB_TOKEN để xác thực push
          GITHUB_TOKEN: ${{ secrets.ENV_GITHUB_TOKEN }}
